services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-alpha
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana-alpha:
    image: grafana/grafana:latest
    container_name: grafana-alpha
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://alpha.tail5f2bae.ts.net:3000
      - GF_SECURITY_ADMIN_USER=arthur
      - GF_SECURITY_ADMIN_PASSWORD=AyaGrafana2025!
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards:ro
      - ./provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
    
  postgres-exporter-alpha:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-alpha
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:Power$$336633$$@host.docker.internal:5432/aya_rag?sslmode=disable
    ports:
      - "9187:9187"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  node-exporter-alpha:
    image: prom/node-exporter:latest
    container_name: node-exporter-alpha
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|private|var/folders)($$|/)'
      - '--no-collector.arp'
      - '--no-collector.bcache'
      - '--no-collector.bonding'
      - '--no-collector.conntrack'
      - '--no-collector.edac'
      - '--no-collector.entropy'
      - '--no-collector.fibrechannel'
      - '--no-collector.hwmon'
      - '--no-collector.infiniband'
      - '--no-collector.ipvs'
      - '--no-collector.mdadm'
      - '--no-collector.nfs'
      - '--no-collector.nfsd'
      - '--no-collector.nvme'
      - '--no-collector.powersupplyclass'
      - '--no-collector.rapl'
      - '--no-collector.schedstat'
      - '--no-collector.selinux'
      - '--no-collector.sockstat'
      - '--no-collector.softnet'
      - '--no-collector.stat'
      - '--no-collector.tapestats'
      - '--no-collector.textfile'
      - '--no-collector.thermal_zone'
      - '--no-collector.timex'
      - '--no-collector.udp_queues'
      - '--no-collector.vmstat'
      - '--no-collector.xfs'
      - '--no-collector.zfs'
    volumes:
      - /:/host:ro
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

